version: '3'

services:
  marvin-dashboard:
    build: .
    image: marvin-dashboard
    container_name: marvin-dashboard-container
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
